# config/tasks.yaml

research_and_profiling_task:
  description: >
    1. Analyze the user's profile: domain '{domain_name}', skills '{skill_sets}', target audience '{target_audience}', and country '{country}'.
    2. Conduct in-depth research using available tools to find current trends, relevant news, recent discussions, common audience questions/pain points, and popular hashtags related to this profile.
    3. Compile all findings into a structured report.
  expected_output: >
    A comprehensive JSON object (conforming to the ResearchFindings Pydantic model). This report must include:
    - trending_topics: List of current trending topics.
    - relevant_news: List of brief news summaries (title, summary, optional source).
    - popular_hashtags: List of relevant and popular hashtags.
    - common_questions_asked: List of questions or pain points of the target audience.
    - engaging_content_formats: List of content formats observed to be engaging for this domain/audience.

content_planning_task:
  description: >
    1. Review the detailed research report and the user's profile (domain '{domain_name}', skills '{skill_sets}', target audience '{target_audience}').
    2. Develop a strategic plan for **one single, highly impactful LinkedIn post**.
    3. This plan must define: a unique post_id (e.g., 'post_datetime_random'), a clear theme_idea, the specific content_type (e.g., 'informational', 'meme', 'learning_snippet'), a concise key_message to convey, and a list of preliminary_hashtags.
  expected_output: >
    A structured JSON object (conforming to the ContentPostOutline Pydantic model) detailing the plan for one LinkedIn post.

linkedin_post_generation_task:
  description: >
    1. Take the provided 'ContentPostOutline' which specifies the theme, content type, and key message.
    2. Write a complete and engaging LinkedIn post body tailored to this plan. The tone should be appropriate for LinkedIn and the target audience.
    3. Finalize a list of relevant and effective hashtags.
    4. Conceptualize a visual element (image, short video idea, meme, pictograph etc.) that would best accompany this post. Describe this visual concept clearly.
    5. Generate a detailed and effective prompt for a text-to-image or text-to-video AI tool to create the suggested visual.
  expected_output: >
    A JSON object (conforming to the LinkedInPostDetail Pydantic model) containing:
    - post_id: The ID from the input plan.
    - theme: The theme from the input plan.
    - content_type: The content type from the input plan.
    - linkedin_post_body: The full, ready-to-publish text of the post.
    - hashtags: A finalized list of hashtags.
    - visual_suggestion: An object detailing the visual_type, its description, and the text_to_media_prompt.